"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/maude-magic.ipynb.

# %% auto 0
__all__ = ['say_hello']

# %% ../nbs/maude-magic.ipynb 4
def say_hello(to):
    print(f"Hello, {to}!")
