"""Execute a maude`s session in Jupyter Lab"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/maude-magic.ipynb.

# %% auto 0
__all__ = ['TIMEOUT', 'TimeoutException', 'MaudeShell', 'MaudeSystem', 'MaudeMagics', 'load_ipython_extension']

# %% ../nbs/maude-magic.ipynb 6
import os
import pexpect
import time
import re
from enum import Flag, auto

# %% ../nbs/maude-magic.ipynb 7
TIMEOUT = 3

class TimeoutException(Exception):
    """Exception raised if time-out."""

    def __init__(self):
        super().__init__("Timeout exception.")
        self.error_code = 1
     
    def __str__(self):
        return f"{self.message} (Error Code: {self.error_code})"    

class MaudeShell:
    """Controls maude execution, executing commands and print responses.
       Preserve sessions between different cell executions."""

    warnings_re = r"^Warning:.*$"
    #messages_re = r"(Advisory|Warning):(.*)\."
    # r"\r\x1b[32mAdvisory: \x1b[0mredefining module \x1b[35mSIMPLE-NAT\x1b[0m.\r\n\rMaude> '
    warnings_reo = re.compile(warnings_re,flags=re.MULTILINE)
        
    trace = False 
    
    def __init__(self,timeout=TIMEOUT):
        """ Spawns maude. """
        self.timeout = timeout
        # Execute maude in environment "env". Add current working directory to MAUDE_LIB
        env = dict(os.environ)
        if not 'MAUDE_LIB' in env: raise(Exception('MAUDE_LIB environmet variable not found'))
        env['MAUDE_LIB'] += ':' + os.getcwd()
        # Expawn maude
        self.sh = pexpect.spawn('maude', encoding='utf-8', env=env)
        self.sh.expect('Maude> ')

    def _sync(self,timeout=TIMEOUT)->str:
        #i = self.sh.expect(['[^-]> ','\rMaude> .*'])
        i = self.sh.expect([pexpect.TIMEOUT,'\rMaude> '],timeout=TIMEOUT)
        if i == 0:
            # if chell is waiting for compleet input, send Control-C
            self.sh.send('\003')
            # and expect for normal response
            self.sh.expect('Maude> ',timeout)
        #self.sh.expect(pexpect.EOF)
        # Normalizamos los fines de linea que devielve Maude. Vamos a eliminar los \r
        return self.sh.before.replace("\r","")    
        
    def __call__(self,command,timeout=TIMEOUT,raises=True,echo=False,trace=False):
        """ Executes 'command" in the shell and checks for messages """
        # Don't terminate session by command
        if command == 'quit .': return ''
        #""" Adds '\n' to command if it don't ends with it. """
        if command[-1] != '\n' : command += '\n'
        if trace: print('Request:\n',repr(command))
        self.sh.send(command)
        response = self._sync()
        if trace: print('Response:\n',repr(response+self.sh.after))
        warnings = self.warnings_reo.findall(response)
        if warnings and raises:
                raise Exception("Warnings:\n"+"\n".join(warnings))
        if echo:
            return response
        else:
            return None        

    def __del__(self):
        self.__call__('quit .')
        

# %% ../nbs/maude-magic.ipynb 23
class MaudeSystem(MaudeShell):
    """Encapsulates maude commands as object methods."""
    identifier = r"(?:[^ :,.()\[\]<>]|[^-]>|`\)|`\()+" 
    red_re = r"^result (?P<sort>"+identifier+"): +(?P<value>.*)$"
    red_reo = re.compile(red_re,re.MULTILINE)
    parse_re = r"^(?P<sort>"+identifier+"): *(?P<value>.*)$"
    parse_reo = re.compile(parse_re,re.MULTILINE)

    
    def __init__(self,timeout=TIMEOUT):
        """ Call base __init__ and compile regular expression objects. """
        super().__init__(timeout)
        __result_pair_RE = r"result *(\w+): *(.*)\r"
        # Compile regular expressions to Regular Expression objects
        #self.__result_pair_REo = re.compile(__result_pair_RE,re.MULTILINE)

    def _getVoidResult(self,command,term)->None:
        """ Executes 'command' over 'term'. Command it's not expected to return a value. """    
        self(command +" " + term.strip() + " .")
        return None
    
    def _getTextResult(self,command,term,trace=False)->str:
        """ Executes 'command' over 'term' expecting a result of text type."""    
        return self(command +" " + term.strip() + " .",echo=True,trace=trace)

    def _getTupleResult(self,command,term,pattern,sort=None,value=None,echo=False,trace=False)->dict:
        """ Executes 'command' over 'term' and uses 'pattern' to fetch result components into a dict witth keys 
            type and value."""
        response = self(command +" " + term.strip()+ " .",echo=True,trace=trace)
        result = pattern.search(response) if isinstance(pattern,re.Pattern) else  re.search(pattern,response)
        if sort  : assert result['sort']  == sort ,f"Type error: expecting {sort}, but found {result[0]}."
        if value : assert result['value'] == value,f"Value error: expecting {value},but found {result[1]}."    
        if result: 
            return result.groupdict() 
        else:
            print(response)
            return None
    
    def load(self,file):
        """ Loads "file" into maude interpreter. """ 
        return self._getVoidResult('load',file)

    def show_module(self,module=""):
        """ Shows module "module" as cell result. By default, shows current module.""" 
        return self._getTextResult('show module',module)
 
    def show_ops(self,module="",filter=None,trace=False):
        pre_result = self._getTextResult('show ops',module,trace=trace)
        # Elimino saltos de linea que no terminan el comando
        pre_result = re.sub('([^.])\\n','\\1 ',pre_result)
        if filter:
            return "\n".join(re.findall(filter,pre_result,flags=re.MULTILINE))
        else:        
            return pre_result

    def show_sorts(self,module="",filter=None,trace=False):
        pre_result = self._getTextResult('show sorts',module,trace=trace)
        if filter:
            return "\n".join(re.findall(filter,pre_result,flags=re.MULTILINE))
        else:        
            return pre_result
    
    def red(self,term,sort=None,value=None,echo=False,trace=False)->dict:
        """ Reduces "term" in current module and returs a "type,value" dictionary.""" 
        return self._getTupleResult('red',term,self.red_reo,sort,value,echo=echo,trace=trace)

    def parse(self,term,sort=None,value=None,trace=False)->dict:
        """ Parses "term" in current module and returns a tupe,"value dictionary".
            Ingnores newlines. """
        term = term.translate({10 : 32, 13 : 32}) 
        return self._getTupleResult('parse',term,self.parse_reo,sort,value,trace=trace)
   
    def __del__(self):
        super().__del__()

    def __get_cmd(self,maude_line):
        """Maps the first word of a response line to a Cmd Enum.
           Returns NoNE if there isn't correspondence. """
        # Skip '> ' from responses.
        maude_line=maude_line.strip()
        if maude_line[0:2] == '> ': maude_line = maude_line[2:]
        if maude_line == 'Maude>' : result = (Cmd.OK,None)
        else: 
            head,blank,tail = maude_line.partition(' ')
            try: result = (Cmd[head.upper()],tail)     
            except: result = (None,None)
        return result


# %% ../nbs/maude-magic.ipynb 52
# This code can be put in any Python module, it does not require IPython
# itself to be running already.  It only creates the magics subclass but
# doesn't instantiate it yet.
# from __future__ import print_function
from IPython.core.magic import (Magics, magics_class, line_magic,
                                cell_magic, line_cell_magic)

# The class MUST call this class decorator at creation time
@magics_class
class MaudeMagics(Magics):
    """Adapts Maude Shell to a IPython Magic class.Uses a owned Maude Shell.
       Cell magics are used to execute maude commands.
       Line magics are used for command line options."""  
    
    __maude_shell = None 
    
    def __init__(self,shell=None):
        # Uses provided naude shell or instantiates one if not 
        __maude_shell = shell if shell else MaudeInterpreter()
        super(MaudeMagics,self).__init__(__maude_shell) 
        # print("on Construntor:"+str(type(self.shell)))
        self.line_counter=0
    
    def get_maude_shell(self):
        return __maude_shell
        
    def prepare_request(self,cell_contents:str)->str:
        """ - Removes leading and trailing empty lines from cell
            - Removes leading and trailing empty lines from each line
            - Terminates each line with \r\n
            - Count efective lines sent to maude shell.
        """
        # print(f"cell_contents at maude()={cell_contents}")
        cell_contents=cell_contents.strip()
        self.before_count =self.line_counter
        request = ""
        for cell_line in cell_contents.split('\n'):
            request+=cell_line.strip()+'\n'
            self.line_counter+=1
        # Maude shell will add trailing \n
        return request
    
    __prepare_request=prepare_request 

    def prepare_response(self,shell_response:tuple)->str:
        """ Ads the count of sent lines at the header of respone,
            to ease sintax error location.
        """    
        response =  f"{self.before_count} (lines sent before.)\n"
        response += ("--------------------------------------------\n")
        for line in shell_response.split('\n'):
            line =  line.strip()
            if line[0]=='>':
                self.before_count += 1
                line = f"{self.before_count:3} {line}"
            response += line + '\n'
        return response
    
    __prepare_response = prepare_response     
           
    @line_cell_magic
    def maude(self, line, cell=None):
        if cell is None:
            result = self.shell(line)
            return result
        else:
            command = line.split()
            if len(command) >=2 and command[0] == "writeTo":    
                with open(command[1],"w") as f:
                    f.write(cell)
            print(self.shell(cell,echo=True))
# In order to actually use these magics, you must register them with a
# running IPython.

def load_ipython_extension(ipython):
    """
    Any module file that define a function named `load_ipython_extension`
    can be loaded via `%load_ext module.path` or be configured to be
    autoloaded by IPython at startup time.º
    """
    # You can register the class itself without instantiating it.  IPython will
    # call the default constructor on it.
    # JSM: or you can register an instance.
    ipython.register_magics(MaudeMagics)
