"""Execute a maude`s session in Jupyter Lab"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/rdf-turtle-jsonld.ipynb.

# %% auto 0
__all__ = ['timeout', 'DEBUG', 'TRACE', 'TimeoutException', 'Cmd', 'MaudeInterpreter', 'MaudeMagics', 'load_ipython_extension']

# %% ../nbs/rdf-turtle-jsonld.ipynb 7
timeout = 3

DEBUG = False
TRACE = False

class TimeoutException(Exception):
    """Exception raised if time-out."""

    def __init__(self):
        super().__init__("Timeout exception.")
        self.error_code = 1

    def __str__(self):
        return f"{self.message} (Error Code: {self.error_code})"    

class Cmd(Flag):
    NONE   = auto()
    OK     = auto()
    LOAD   = auto()
    SHOW   = auto()
    FTH    = auto()
    TH     = auto()
    FMOD   = auto()
    MOD    = auto()
    VIEW   = auto()
    ENDFTH = auto()
    ENDTH  = auto()
    ENDFM  = auto()
    ENDM   = auto()
    ENDV   = auto()
    REDUCE = auto()
    parse  = auto()
    RESULT = auto()
    READ   = FTH | TH | FMOD | MOD | VIEW
    END_READ   = ENDFTH | ENDTH | ENDFM | ENDM | ENDV
    


class MaudeInterpreter:
    """Controls maude execution, executing commands and print responses.
       Preserve sessions between different cell executions."""

    class State(Flag):
        IDLE     = auto()
        READING  = auto()
        REDUCING = auto()
        SHoWING  = auto()

    red_re = r"result (?P<sort>(\w|')+): *(?P<value>.*)\r"
    red_reo = re.compile(red_re)
    parse_re = r"(?P<sort>(\w|')+): *(?P<value>.*)\r"
    parse_reo = re.compile(parse_re)
    messages_re = r"^(.*)(Advisory|Warning):(.*)\."
    # r"\r\x1b[32mAdvisory: \x1b[0mredefining module \x1b[35mSIMPLE-NAT\x1b[0m.\r\n\rMaude> '
    messages_reo = re.compile(messages_re,flags=re.MULTILINE)

    
    def __init__(self,timeout=timeout):
        """ Init variables and spawns maude. """
        self.state = MaudeInterpreter.State.IDLE
        # Regular expressions to scan outputs
        __result_pair_RE = r"result *(\w+): *(.*)\r"

        self.timeout = timeout
        # Execute maude in environment "env". Add current working directory to MAUDE_LIB
        env = dict(os.environ)
        if not 'MAUDE_LIB' in env: raise(Exception('MAUDE_LIB environmet variable not found'))
        env['MAUDE_LIB'] += ':' + os.getcwd()
        if DEBUG: 
            print(f"MAUDE_LIB={env['MAUDE_LIB']}")
            
        # Compile regular expressions to Regular Expression objects
        self.__result_pair_REo = re.compile(__result_pair_RE,re.MULTILINE)

        # The expawned process:
        self.sh = pexpect.spawn('maude --no-advise', encoding='utf-8', env=env)
        self.sh.expect('Maude> ')
        self._sync()    

    def getTupleResult(self,command,term,pattern,sort=None,value=None)->dict:
        """ Executes 'command' over 'term' and uses 'pattern' to fetch result components into a tuple.
            Tuple is (Type,Value).
            If Type and/or Value ara suplied, checks match.
        """    
        self.sh.send(command +" " + term.strip() + " .\n")
        self._sync()
        response = self.sh.before
        # print(response)
        result = pattern.search(response) if isinstance(pattern,re.Pattern) else  re.search(pattern,response)
        if sort  : assert result['sort']  == sort ,f"Type error: expecting {sort}, but found {result[0]}."
        if value : assert result['value'] == value,f"Value error: expecting {value},but found {result[1]}."    
        if result: 
            return result.groupdict() 
        else:
            print(response)
            return None
    

    def __filter_messages(self,response):
        # print(repr(response)) 
        result=""
        for message in self.messages_reo.findall(response):
            print("message=",message)
            message_line = f"{message[0]}{message[1]} :{message[2]}"
            #assert message[1]=="Advisory",message_line
            result += message_line+"\n"
        return result
        
    def red(self,term,sort=None,value=None)->dict:
        return self.getTupleResult('red',term,self.red_reo,sort,value)

    def parse(self,term,sort=None,value=None)->dict:
        return self.getTupleResult('parse',term,self.parse_reo,sort,value)
   
    def _sync(self):
        """ We syncrhonize with maude shell requesting a pwd.""" 
        self.sh.sendline('pwd')
        self.sh.expect('pwd.*Maude> ')
            
    def __del__(self):
        if DEBUG: print('Destroying object')
        self.__call__('quit .')

    def __get_cmd(self,maude_line):
        """Maps the first word of a response line to a Cmd Enum.
           Returns NoNE if there isn't correspondence. """

        if TRACE: print(f"\t\t__get_cmd({maude_line})=",end="")        
        # Skip '> ' from responses.
        maude_line=maude_line.strip()
        if maude_line[0:2] == '> ': maude_line = maude_line[2:]
        if maude_line == 'Maude>' : result = (Cmd.OK,None)
        else: 
            head,blank,tail = maude_line.partition(' ')
            try: result = (Cmd[head.upper()],tail)     
            except: result = (None,None)
        if TRACE: print(f"{result}")                
        return result

    def __post_process_response(self,response:str)->tuple:    
        """ Init State Machine for processing lines."""
        if TRACE: print(f"__post_process(response)")
        response_lines = filter(None,response.splitlines())
        self.state  = MaudeInterpreter.State.IDLE
        self.output = None
        self.__buffer = ""
        
        for line in response_lines:
                self.__process_response_line(line)
        if TRACE: print(f"\toutput:{self.output}")
        return self.output

    def __process_response_line(self,response_line):
        """ Makes MaudeInterpreter State Machine accept response line.
            Returns response (if proceed), None otherwise.
            Response can be:
               - None, if input at current state don't produce result,  
               - a String generic response.
               - a 2-tuple (Type,value) as a result of maude command
        """ 
        # A response_line implies a posible maude command
        # Each maudecommand or None (command) is processed at current state, producing an output or None .
        if TRACE: print(f"\t__process_response_line({response_line}) in current State:{self.state.name}")
        self.__buffer += response_line+ '\n' 
        command,args = self.__get_cmd(response_line)
        current_state  = self.state
        new_state      = self.state
        match self.state:
            case MaudeInterpreter.State.IDLE: 
                match command:
                    case None       : output = None
                    case Cmd.OK     : output = None
                    case Cmd.LOAD   : output = None
                    case Cmd.READ   : new_state = MaudeInterpreter.State.READING  ; output = None ; 
                    case Cmd.REDUCE : new_state = MaudeInterpreter.State.REDUCING ; output = None  
                    case Cmd.SHOW   : new_state = MaudeInterpreter.State.SHoWING  ; output = None ; 
                    case Cmd.VIEW | Cmd.FMOD: 
                                      new_state = MaudeInterpreter.State.READING  ; output = None ; 
            case MaudeInterpreter.State.REDUCING:
                match command:
                   case None : output = None 
                   case Cmd.RESULT: 
                       type_,dot,value = args.partition(':')
                       output = (type_,value)
                   case Cmd.OK   : new_state = MaudeInterpreter.State.IDLE ; output = None
            case MaudeInterpreter.State.SHoWING:
                match command:
                    case None                 :  output = None
                    case Cmd.FMOD | Cmd.ENDFM :  output = None    
                    case Cmd.OK  : new_state = MaudeInterpreter.State.IDLE ; output = (None,self.__buffer)
            case MaudeInterpreter.State.READING:
                match command:
                    case None         :  output = None 
                    case Cmd.VIEW | Cmd.FMOD : output = None     
                    case Cmd.ENDV | Cmd.ENDFM: output = None 
                    case Cmd.OK       : new_state = MaudeInterpreter.State.IDLE ; output = self.__buffer    
        self.state = new_state               
        
        try:
            output
        except NameError:
            raise Exception(f"STATE MACHINE:output value for input {command} at state {current_state} is not defined." )
        if output:  self.output = output
        if TRACE: print(f"\t\tNew state: {self.state.name}.\n\t\toutput: {output}.")
   
    def __pre_process_request(self,request):
        return request
        request_lines = request.splitlines()
        for line in request_lines:
            if line: 
                maude_cmd,blank,args = line.partition(' ')
                self.__next_state(maude_cmd)
        return request

    # Cmmand processing
    def __call__(self,command,timeout=timeout):
        """ Adds '\n' to command if it don't terminate with it. """
        # Don't terminate session by command
        if DEBUG: print(f"original Command = {repr(command)}")
        if command == 'quit .': return ''
        # strip command before send
        # print(f"<--{repr(command.strip())}")
        if command[-1] != '\n' : command += '\n'
        #print(f"Sent Command = {repr(command)}")
        self.sh.send(self.__pre_process_request(command))
        self._sync()
        #print(f"-->{repr(self.sh.before)+repr(self.sh.after)}")
        response = self.sh.before
        # filter response
        return self.__filter_messages(response)
        

# %% ../nbs/rdf-turtle-jsonld.ipynb 23
# This code can be put in any Python module, it does not require IPython
# itself to be running already.  It only creates the magics subclass but
# doesn't instantiate it yet.
# from __future__ import print_function
from IPython.core.magic import (Magics, magics_class, line_magic,
                                cell_magic, line_cell_magic)

# The class MUST call this class decorator at creation time
@magics_class
class MaudeMagics(Magics):
    """Adapts Maude Shell to a IPython Magic class.Uses a owned Maude Shell.
       Cell magics are used to execute maude commands.
       Line magics are used for command line options."""  
    
    __maude_shell = None 
    
    def __init__(self,shell=None):
        # Uses provided naude shell or instantiates one if not 
        __maude_shell = shell if shell else MaudeInterpreter()
        super(MaudeMagics,self).__init__(__maude_shell) 
        # print("on Construntor:"+str(type(self.shell)))
        self.line_counter=0
    
    def get_maude_shell(self):
        return __maude_shell
        
    def prepare_request(self,cell_contents:str)->str:
        """ - Removes leading and trailing empty lines from cell
            - Removes leading and trailing empty lines from each line
            - Terminates each line with \r\n
            - Count efective lines sent to maude shell.
        """
        # print(f"cell_contents at maude()={cell_contents}")
        cell_contents=cell_contents.strip()
        self.before_count =self.line_counter
        request = ""
        for cell_line in cell_contents.split('\n'):
            request+=cell_line.strip()+'\n'
            self.line_counter+=1
        # Maude shell will add trailing \n
        return request
    
    __prepare_request=prepare_request 

    def prepare_response(self,shell_response:tuple)->str:
        """ Ads the count of sent lines at the header of respone,
            to ease sintax error location.
        """    
        response =  f"{self.before_count} (lines sent before.)\n"
        response += ("--------------------------------------------\n")
        for line in shell_response.split('\n'):
            line =  line.strip()
            if line[0]=='>':
                self.before_count += 1
                line = f"{self.before_count:3} {line}"
            response += line + '\n'
        return response
    
    __prepare_response = prepare_response     
           
    @line_cell_magic
    def maude(self, line, cell=None):
        if cell is None:
            #print("MaudeInterpreter:","shell line=",line)
            result = self.shell(self.prepare_request(line))
            #print("MaudeInterpreter:",'result=',result)
            return result
        else:
            # print(f"cell at maude()={cell}")
            # ToDo: migrar el cálculo del nº de línea a MaudeInterpreter
            # print(self.prepare_response(self.shell(self.prepare_request(cell))))
            print(self.shell(self.prepare_request(cell)))

# In order to actually use these magics, you must register them with a
# running IPython.

def load_ipython_extension(ipython):
    """
    Any module file that define a function named `load_ipython_extension`
    can be loaded via `%load_ext module.path` or be configured to be
    autoloaded by IPython at startup time.
    """
    # You can register the class itself without instantiating it.  IPython will
    # call the default constructor on it.
    # JSM: or you can register an instance.
    ipython.register_magics(MaudeMagics)
