"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/maude-magic.ipynb.

# %% auto 0
__all__ = ['MaudeInterpreter', 'say_hello']

# %% ../nbs/maude-magic.ipynb 5
class MaudeInterpreter:
    """Controls maude execution, executing commands and print responses.
       Preserve sessions between different cell executions."""
    def __init__(self,debug=False,timeout=2):
        """ Init variables and spawns maude. """
        self.debug,self.timeout = debug,timeout
        # Execute maude in environment. Add current working directory to MAUDE_LIB
        env = dict(os.environ)
        if not 'MAUDE_LIB' in env: raise(Exception('MAUDE_LIB environmet variable not found'))
        env['MAUDE_LIB'] += ';' + os.getcwd()
        if debug: 
            print(f"MAUDE_LIB={env['MAUDE_LIB']}")
        # the expawned process:
        self.sh = pexpect.spawn('maude', encoding='utf-8', env=env)
        self.sh.expect('Maude>')
        if debug: print(self.sh.before)

# %% ../nbs/maude-magic.ipynb 8
def say_hello(to):
    print(f"Hello, {to}!")
